### ISSUE TITLE
missing requests module for NS1 provider

### ISSUE THREAD

**Issue by rseste-daitan** [octodns/octodns-ns1#14]
The `requests` module is missing in the setup.py
If you install it using pip, octodns-ns1 module works partially. Without `requests` module it uses the basic transport from ns1-python which has some different responses
When octodns need to create a new zone it first checks if it exists. But the response is different from the expected one so it fails and stop execution. 
In order to fix we just need to add the `requests` module in the setup.py

**Comment by rseste-daitan** [comment]
I've opened a PR to fix this
https://github.com/octodns/octodns-ns1/pull/13

**Comment by viranch** [comment]
Fixed by #13
