### ISSUE TITLE
Fix error handling for basic transport

### ISSUE THREAD

**Issue by viranch** [octodns/octodns-ns1#15]
Creating an issue out of this comment https://github.com/octodns/octodns-ns1/pull/13#issuecomment-1064490898

/cc @rseste-daitan

**Comment by rseste-daitan** [comment]
I created an issue yesterday. I think we can close one of them. they are
duplicated.

https://github.com/octodns/octodns-ns1/issues/14


*Rafael Seste**, Systems Architect*

+55 (19) 99230.4039


*DAITAN |* *Accelerating **|* www.daitan.com

*Privileged and confidential. If this message has been received in error,
please notify the sender and delete it immediately.*

*Conteúdo confidencial. Se esta mensagem foi recebida por engano, favor
avisar o remetente e apagá-la imediatamente.*

**Comment by viranch** [comment]
#14 is closed after the quick fix #13 was merged. This is to address the root cause.
