### ISSUE TITLE
NS1 CNAME weighting causes octodns-dump exception

### ISSUE THREAD

**Issue by jeff-blank** [octodns/octodns-ns1#4]
when a CNAME record in NS1 has two answers due to weighting, an error occurs in octodns-dump:

```
  File "/[...]/.pyenv/versions/2.7.17/Python.framework/Versions/2.7/lib/python2.7/site-packages/octodns/provider/ns1.py", line 633, in _data_for_CNAME
    value = record['short_answers'][0]
KeyError: u'short_answers'
```

there appears to be no `records['short_answers']` in this case, so as you can see above, a `KeyError` is thrown, while https://github.com/github/octodns/blob/master/octodns/provider/ns1.py#L636 only allows for an `IndexError`. I've worked around it by changing the line to

```
        except (IndexError, KeyError):
```

but I have no idea whether that's the correct approach, so I'm opening this as an issue rather than a PR.

**Comment by viranch** [comment]
This should now be fixed (by #704 & #799).

@jeff-blank can you try again with latest master of octodns and `main` of octodns-ns1?

**Comment by jeff-blank** [comment]
unfortunately I cannot test, as I am no longer employed where I encountered the issue.

**Comment by viranch** [comment]
Thank you for the quick note. I remembering running into this exception before CNAME dynamic records were supported, which was added by above PRs.

Going to close this unless someone can still repro the problem and reopen the issue.
