### ISSUE TITLE
Creating new zone with root NS fails

### ISSUE THREAD

**Issue by viranch** [octodns/octodns-ns1#48]
Applying a new zone yaml with root NS fails with "record already exists" error, which is likely because the plan wants to create the root NS but after the zone is created, the record also shows up, and trying to create root NS then results in that error.

**Comment by ross** [comment]
Not surprising. Probably other providers have the same issue. I think it's come up with and been fixed in at least once. Suspect the fix will be to see the `exists=False` and convert the root NS create to an update in the provider.

**Comment by ross** [comment]
Fixed by https://github.com/octodns/octodns-ns1/pull/64
